name: 'Docker over SSH'
description: 'Setup connection to remote Docker Daemon through SSH'
branding:
  icon: anchor
  color: blue
inputs:
  host:
    description: 'Remote host'
    required: true
  port:
    description: 'SSH port'
    required: false
    default: '22'
  user:
    description: 'SSH user'
    required: true
    default: root
  key:
    description: 'Content of SSH private key'
    required: true
  key_path:
    description: 'Path to the SSH private key'
    required: false
    default: '/home/runner/.ssh/id_rsa'
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        INPUT_KEY: ${{ inputs.key }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_USER: ${{ inputs.user }}
        INPUT_KEY_PATH: ${{ inputs.key_path }}
      run: |
        mkdir -p ~/.ssh
        echo "$INPUT_KEY" > $INPUT_KEY_PATH
       
