name: Build app image and publish to registry

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name:  Build app image and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Collect meta for docker tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/dtp-stat/dtp-stat
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Log in to DO Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          registry: registry.digitalocean.com
      
      - name: Build app image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show applyed tags
        run: echo "::set-output name=version::${{ steps.meta.outputs.tags }}"