# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy and run image

on:
  workflow_dispatch:
   inputs:
      version:
        description: 'Docker version label'
        required: true
        default: 'latest'
jobs:
  deploy_from_regestry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: ./.github/actions/docker-ssh
        with:
          host: ${{ secrets.STAGING_HOST }}
          key: ${{ secrets.STAGING_KEY }}

      - run: |
          ssh root@${{ secrets.STAGING_HOST }} << EOF
          docker rm -f dtpstat-app-cli
          docker run --pull=always --network host --entrypoint ./manage.py --name dtpstat-app-cli --env-file /etc/dtpstat.env registry.digitalocean.com/dtp-stat/dtp-stat:${{ github.event.inputs.version }} migrate
          docker stop dtpstat-app
          docker rm dtpstat-app
          docker run -d --pull=always --network host --name dtpstat-app --env-file /etc/dtpstat.env registry.digitalocean.com/dtp-stat/dtp-stat:${{ github.event.inputs.version }}
          docker rm -f dtpstat-app-cli-dtp dtpstat-app-cli-opendata
          docker create -v /var/www/media:/app/media --pull=always --network host --name dtpstat-app-cli-dtp --env-file /etc/dtpstat.env registry.digitalocean.com/dtp-stat/dtp-stat:${{ github.event.inputs.version }} dtp
          docker create -v /var/www/media:/app/media --pull=always --network host --name dtpstat-app-cli-opendata --env-file /etc/dtpstat.env registry.digitalocean.com/dtp-stat/dtp-stat:${{ github.event.inputs.version }} opendata
          EOF