# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy and run image

on: workflow_dispatch

jobs:
  deploy_from_regestry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/dtp-stat/dtp-stat
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha


      - name: Install SSH Key
        uses: ./.github/actions/docker-ssh
        with:
          host: ${{ secrets.STAGING_HOST }}
          key: ${{ secrets.STAGING_KEY }}

      - run: |
          ssh root@${{ secrets.STAGING_HOST }} << EOF
          docker rm dtpstat-app-cli
          docker run --pull=always --network host --entrypoint ./manage.py --name dtpstat-app-cli --env-file /etc/dtpstat.env ${{ steps.meta.outputs.version }} migrate
          docker stop dtpstat-app
          docker rm dtpstat-app
          docker run -d --pull=always --network host --name dtpstat-app --env-file /etc/dtpstat.env ${{ steps.meta.outputs.version }}
          EOF