name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    services:
      postgis:
        image: kartoza/postgis:12.0
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y binutils gdal-bin python3-gdal libgdal-dev libproj-dev
    - name: Run Tests
      env:
        SECRET_KEY: secret
        DATABASE_URL: 'postgis://docker:docker@localhost:5432/gis'
        STATIC_ROOT: '/static'
        STATICFILES_DIRS: '/staticfiles'
        RECAPTCHA_PUBLIC_KEY: test
        RECAPTCHA_PRIVATE_KEY: test
        DEBUG: 1
        PROJECT_PATH: /code
      run: |
        pytest -v

